config/routes.rb
Rails.application.routes.draw do
  root :to => 'confusion_matrices#index'
  get 'confusion_matrices/new' => 'confusion_matrices#new'
end

app/models/params_set.rb
class ParamsSet < ActiveRecord::Base
end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/confusion_matrices_controller.rb
class ConfusionMatricesController < ApplicationController
  def index
  end

  def new
    @result = Result.new
  end

  def create
    @result = Result.new(params.require(:result).permit(:params_set_id))

    if @result.save
      redirect_to root_url
    else
      render :new, status: 422
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/confusion_matrices/index.html.haml
.container
  "confusion_matrices"

app/views/confusion_matrices/new.html.haml
.container
  = form_for @result, url: confusion_matrices_new_path do |f|
    = f.collection_select :params_set_id, ParamsSet.all, :id, :name, { class: 'collection-select' }, { id: 'select-result-form' }

  = image_tag '1.jpg', { class: 'confusion-matrix-image' }

= javascript_include_tag 'confusion_matrices'

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = yield